# Generated by Django 5.0.4 on 2024-06-24 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_no_of_purchases_courses_no_of_registrations'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Courses',
            new_name='Course',
        ),
    ]
