# Generated by Django 5.0.4 on 2024-07-11 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_coursechapter_remove_course_time_to_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursechapter',
            name='time_to_complete',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
