# Generated by Django 5.0.4 on 2024-07-11 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_coursechapter_time_to_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='courseData',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.coursechapter'),
            preserve_default=False,
        ),
    ]
