# Generated by Django 5.0.4 on 2024-07-11 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_course_coursedata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='courseData',
        ),
        migrations.AddField(
            model_name='coursechapter',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='api.course'),
            preserve_default=False,
        ),
    ]
