# Generated by Django 5.0.4 on 2024-07-15 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_cart_updated_at_remove_cartitem_added_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='rating',
            field=models.FloatField(default=0),
        ),
    ]
