# Generated by Django 5.0.4 on 2024-07-16 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_course_coursedata'),
        ('api', '0012_course_rating'),
    ]

    operations = [
    ]
