# Generated by Django 5.0.4 on 2024-07-16 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_merge_0008_course_coursedata_0012_course_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='courseData',
        ),
        migrations.CreateModel(
            name='BoughtCourses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bought_at', models.DateTimeField(auto_now_add=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.cart')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.course')),
            ],
        ),
    ]
