# Generated by Django 5.0.4 on 2024-07-18 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_course_coursedata_boughtcourses'),
    ]

    operations = [
        migrations.AddField(
            model_name='boughtcourses',
            name='completed_chapters',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='boughtcourses',
            name='total_chapters',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
