# Generated by Django 5.0.4 on 2024-07-20 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_quiz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='solved_at',
            field=models.DateTimeField(blank=True),
        ),
    ]
