# Generated by Django 5.0.4 on 2024-08-14 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_remove_quiz_solved_at_userquiz'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveOtps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('otp', models.IntegerField(max_length=6)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
