# Generated by Django 5.0.4 on 2024-08-14 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_activeotps'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ActiveOtps',
        ),
    ]
