# Generated by Django 5.0.4 on 2024-06-13 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='userlogin',
        ),
    ]
