# Generated by Django 5.0.4 on 2024-08-14 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_activeotps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activeotps',
            name='otp',
            field=models.IntegerField(),
        ),
    ]
